# Generated by Django 4.2.3 on 2023-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
            ],
        ),
    ]
