# Generated by Django 4.2.3 on 2023-07-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issue_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='recipient_name',
            new_name='name',
        ),
    ]
