# Generated by Django 4.2.3 on 2023-07-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='title',
            new_name='signature',
        ),
    ]
